PurpicsApps/PurpicsWeb/Areas/Admin/ViewModels/AccountInformation/AccontStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PurpicsWeb.Areas.Admin.ViewModels.AccountInformation
{
    public class AccontStatus
    {
        public int Status { get; set; }
        public string Message { get; set; }
    }
}

PurpicsApps/PurpicsWeb/Areas/Admin/ViewModels/AccountInformation/AccountInformation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PurpicsWeb.Areas.Admin.ViewModels.AccountInformation
{
    public class AccountInformation
    {
        public int UserId { get; set; }
        [EmailAddress(ErrorMessage = "Please enter valid Email Address.")]
        public string EmailAddress { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
    public class AccountEmail
    {
        public int UserId { get; set; }
        
        [Required(ErrorMessage = "Please enter Email address.")]
        [EmailAddress(ErrorMessage = "Please enter valid Email Address.")]
        public string EmailAddress { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

PurpicsApps/PurpicsWeb/Areas/Charity/Models/AccountInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PurpicsWeb.Areas.Charity.Models
{
    public class AccountInformation
    {
        public AccountInformation()
        {
            CharityId = 0;
            EmailAddress = string.Empty;
            Password = string.Empty;
            ContactName = string.Empty;
            PhoneNumber = string.Empty;
            AboutCharity = string.Empty;
            LegalEntityName = string.Empty;
            Number501_C3 = string.Empty;
            Address = string.Empty;
            CharityName = string.Empty;
            CharityLogo = null;

            CategoryName = string.Empty;
            CharityLogoFullPath = string.Empty;
            CategoryId = 0;
            Categories = new List<SelectListItem>();
            Status = string.Empty;
            CreditCardDetails = new CreditCardDetails();
        }

        public int CharityId { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string AboutCharity { get; set; }
        public string LegalEntityName { get; set; }
        public string Number501_C3 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CharityName { get; set; }
        public HttpPostedFileBase CharityLogo { get; set; }

        public string CategoryName { get; set; }
        public string CharityLogoFullPath { get; set; }
        public int CategoryId { get; set; }
        public List<SelectListItem> Categories { get; set; }
        public string Status { get; set; }
        public CreditCardDetails CreditCardDetails { get; set; }

    }

}

PurpicsApps/PurpicsWeb/Areas/Company/Models/AccountInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PurpicsWeb.Areas.Company.Models
{
    public class AccountInformation
    {
        public AccountInformation()
        {
            CompanyId = 0;
            EmailAddress = string.Empty;
            Password = string.Empty;
            ContactName = string.Empty;
            PhoneNumber = string.Empty;
            AboutCompany = string.Empty;
            LegalEntityName = string.Empty;
            Number501_C3 = string.Empty;
            Address = string.Empty;
            CompanyName = string.Empty;
            CharityLogo = null;            
            CompanyLogoFullPath = string.Empty;
            
            
            Status = string.Empty;
            CreditCardDetails = new CreditCardDetails();
        }

        public int CompanyId { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string AboutCompany { get; set; }
        public string LegalEntityName { get; set; }
        public string Number501_C3 { get; set; }
        public string Address { get; set; }
        public string CompanyName { get; set; }
        public HttpPostedFileBase CharityLogo { get; set; }
        
        public string CompanyLogoFullPath { get; set; }
        
        
        public string Status { get; set; }
        public CreditCardDetails CreditCardDetails { get; set; }
    }
}

PurpicsApps/PurpicsWeb/Areas/StudentOrganization/Models/AccountInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PurpicsWeb.Areas.StudentOrganization.Models
{
    public class AccountInformation
    {
        public AccountInformation()
        {
            StudentOrganizationId = 0;
            EmailAddress = string.Empty;
            Password = string.Empty;
            ContactName = string.Empty;
            PhoneNumber = string.Empty;
            Address = string.Empty;
            Name = string.Empty;
            Logo = null;
            CategoryName = string.Empty;
            StudentOrgLogoFullPath = string.Empty;
            CategoryId = 0;
            Categories = new List<SelectListItem>();
            Status = string.Empty;
        }

        public int StudentOrganizationId { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Name { get; set; }
        public HttpPostedFileBase Logo { get; set; }
        public string CategoryName { get; set; }
        public string StudentOrgLogoFullPath { get; set; }
        public int CategoryId { get; set; }
        public List<SelectListItem> Categories { get; set; }
        public string Status { get; set; }
        public List<SOCharities> SOCharities { get; set; }

    }

    public class SOCharities
    {
        public SOCharities()
        {
        }

        public int CharityId { get; set; }
        public string CharityName { get; set; }
        public bool IsSelected { get; set; }
    }
}

PurpicsApps/PurpicsWeb/Areas/Admin/Controllers/AccountInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PurpicsWeb.Areas.Admin.ViewModels.AccountInformation;
using Microsoft.AspNet.Identity;
using PurpicsWeb_DL.Entities;
using PurpicsWeb_DL.Repositories;
using PurpicsWeb.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Threading.Tasks;
using PurpicsWeb.Services.CommonFunctions;
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Text;


namespace PurpicsWeb.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AccountInformationController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        // GET: Admin/AccountInformation
        public ActionResult Index()
        {
            AccountEmail objAccountInformtion = new AccountEmail();
            string userid = HttpContext.User.Identity.GetUserId();
            AspNetUsers user = Repository<AspNetUsers>.GetEntityListForQuery(x => x.Id == userid).FirstOrDefault();
            objAccountInformtion.EmailAddress = user.Email;
            objAccountInformtion.OldPassword = "********";
            //objAccountInformtion.Password = user.PasswordHash;
            return View("~/Areas/Admin/Views/AccountInformation/AccountInformation.cshtml", objAccountInformtion);
        }
        //public ActionResult AccountInformation()
        //{
        //    AccountInformation objAccountInformtion = new AccountInformation();
        //    string userid = HttpContext.User.Identity.GetUserId();
        //    AspNetUsers user = Repository<AspNetUsers>.GetEntityListForQuery(x => x.Id == userid).FirstOrDefault();
        //    objAccountInformtion.EmailAddress = user.Email;
        //    //objAccountInformtion.Password = user.PasswordHash;
        //    return View(objAccountInformtion);
        //}
        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        public async Task<ActionResult> ChangePassword(AccountInformation model)
        {
            //AccountEmail objAccountInformtion = new AccountEmail();
            //string userid = HttpContext.User.Identity.GetUserId();
            //AspNetUsers user = Repository<AspNetUsers>.GetEntityListForQuery(x => x.Id == userid).FirstOrDefault();
            //objAccountInformtion.EmailAddress = user.Email;
            //model.EmailAddress = user.Email;

            //if (!ModelState.IsValid)
            //{
            //    return View("~/Areas/Admin/Views/AccountInformation/AccountInformation.cshtml", objAccountInformtion);
            //}
            //var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            //if (result.Succeeded)
            //{
            //    TempData["SuccessConfirmationMessage"] = "Your password has been changed.";
            //    return RedirectToAction("", "AccountInformation");
            //}
            //AddErrors(result);
            //return View("~/Areas/Admin/Views/AccountInformation/AccountInformation.cshtml", objAccountInformtion);



            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user == null)
            {
                return Json(-2, JsonRequestBehavior.AllowGet);//Invalid AspNetUserId.

            }
            var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                return Json(new AccontStatus { Status = 1, Message = "Password changed successfully" }, JsonRequestBehavior.AllowGet);//Password changed
            }
            else
            {
                StringBuilder errorMessages = new StringBuilder();
                foreach( var message in result.Errors)
                {
                    errorMessages.Append(message);
                }

                return Json(new AccontStatus { Status=-1 ,Message=errorMessages.ToString() }, JsonRequestBehavior.AllowGet);//Old password is not valid.
            }
        }
        public ActionResult EditEmail()
        {
            return View();
        }
        public ActionResult EditPassword()
        {
            AccountInformation objAccountInformtion = new AccountInformation();
            string userid = HttpContext.User.Identity.GetUserId();
            AspNetUsers user = Repository<AspNetUsers>.GetEntityListForQuery(x => x.Id == userid).FirstOrDefault();
            objAccountInformtion.EmailAddress = user.Email;
            //objAccountInformtion.Password = user.PasswordHash;
            return View("~/Areas/Admin/Views/AccountInformation/EditPassword.cshtml", objAccountInformtion);
        }


        //
        // POST: /Manage/Email
        [HttpPost]
        public async Task<ActionResult> ChangeEmail(AccountEmail model)
        {
            AccountEmail objAccountInformtion = new AccountEmail();
            string userid = HttpContext.User.Identity.GetUserId();

            bool lsIsExist = IsEmailAlreadyExist(model.EmailAddress, userid);
            if (lsIsExist == false)
            {
                try
                {
                    //ApplicationDbContext context = new ApplicationDbContext();
                    //UserStore<ApplicationUser> store = new UserStore<ApplicationUser>(context);
                    //ApplicationUser cUser = await store.FindByIdAsync(userid);
                    //cUser.UserName = model.EmailAddress;
                    //cUser.Email = model.EmailAddress;
                    //await store.UpdateAsync(cUser);
                    //await SignInManager.SignInAsync(cUser, true, true);
                    
                    var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                    user.Email = model.EmailAddress;
                    user.UserName = model.EmailAddress;
                    var result = await UserManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        await SignInManager.SignInAsync(user, true, true);
                        return Json(new AccontStatus { Status=1 ,Message="Your email has been changed." }, JsonRequestBehavior.AllowGet);//Password changed
                    }
                    else
                    {
                        StringBuilder errorMessages = new StringBuilder();
                        foreach (var message in result.Errors)
                        {
                            errorMessages.Append(message);
                        }
                        return Json(new AccontStatus { Status = 0, Message = errorMessages.ToString() }, JsonRequestBehavior.AllowGet);//Password changed
                    }

                    //TempData["SuccessConfirmationMessage"] = "Your email has been changed.";
                }
                catch
                {
                    //TempData["ErrorMsg"] = "An error occured while updating email.";
                    return Json(new AccontStatus { Status = -1, Message = "An error occured while updating email." }, JsonRequestBehavior.AllowGet);//Password changed
                }
            }
            else
            {
                //TempData["ErrorMsg"] = "Email is already exist.";
                return Json(new AccontStatus { Status = -1, Message = "Email is already exist." }, JsonRequestBehavior.AllowGet);//Password changed

            }
            //return RedirectToAction("", "AccountInformation");
            //return View("~/Areas/Admin/Views/AccountInformation/AccountInformation.cshtml", objAccountInformtion);
        }
        private bool IsEmailAlreadyExist(string fsEmail, string fsId)
        {
            bool lsIsExist = false;
            AspNetUsers user = Repository<AspNetUsers>.GetEntityListForQuery(x => x.Email == fsEmail && x.Id != fsId).FirstOrDefault();
            if (user != null)
                lsIsExist = true;

            return lsIsExist;
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

PurpicsApps/PurpicsWeb/Areas/Charity/Views/AccountInformation/AccountInformation.cshtml
@model PurpicsWeb.Areas.Charity.Models.AccountInformation
@{
    ViewBag.Title = "Account Information";
    Layout = "~/Areas/Charity/Views/Shared/_CharityLayout.cshtml";
}

<style>
    .account-main .compaigns-form {
        height: 100% !important;
    }

    .compaigns-form form-horizontal left col-xs-12 {
        height: 100% !important;
    }
</style>

@using (Html.BeginForm("EditAccountInformation", "AccountInformation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="col-md-9 col-sm-8 col-xs-12 padding-zero">
        <div class="col-xs-12 breadcrumbs">
            <a href="@Url.Action("", "ManageDashboard", new { area = "Charity" })" title="Home">Home</a><i class="fa fa-angle-right"></i>
            <span>Account Information</span>
        </div>
        <div class="col-xs-12 padding-zero">
            <hr />
        </div>
        <div class="col-xs-12 main-title">
            <h1 class="pull-left">Account Information</h1>
            <span class="pull-right">Status: <strong>@Html.DisplayFor(m => m.Status)</strong></span>
        </div>
        <div class="col-xs-12 account-main">
            <div class="compaigns-form form-horizontal left col-xs-12" id="divGeneralInfo">
                <div class="col-xs-12 padding-zero">
                    <div class="form-group">
                        <label class="col-sm-8 control-label info">General Information:</label>
                        <div class="col-sm-4 control-label agree">
                            @Html.ActionLink("Edit", "EditAccountInformation", "AccountInformation", new { CharityId = @Model.CharityId }, new { @class = "btn btn-default active pull-right", @title = "Edit Account Information", @id= "lnkEditAccountInfo_loader" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Username:</label>
                        <div class="col-sm-8 control-label" style="overflow-wrap: break-word;">
                            <span>@Html.DisplayFor(m => m.EmailAddress)</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Password:</label>
                        <div class="col-sm-8 control-label">
                            @*<span><a href="@Url.RouteUrl("Default", new { controller="Manage" , action="ChangePassword" })" title="Change Password">Change Password</a></span>*@
                            <span>********</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Contact Name:</label>
                        <div class="col-sm-8 control-label wrapcontent" style="overflow-wrap: break-word;">
                            <span>@Html.DisplayFor(m => m.ContactName, new { @class = "form-control" })</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Contact Phone:</label>
                        <div class="col-sm-8 control-label">
                            <span>@Html.DisplayFor(m => m.PhoneNumber, new { @class = "form-control", @maxlength = "12" })</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">About Charity:</label>
                        <div class="col-sm-8 control-label wrapcontent" style="overflow-wrap: break-word;">
                            <span>
                                @Html.DisplayFor(m => m.AboutCharity, new { @class = "form-control" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="compaigns-form form-horizontal right pull-right col-xs-12" id="divOtherInfo">
                <div class="col-xs-12 padding-zero">
                    <div class="form-group">
                        <label class="col-sm-8 control-label info">Other Information:</label>
                        <div class="col-sm-4 control-label">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Legal Entity Name:</label>
                        <div class="col-sm-8 control-label wrapcontent" style="overflow-wrap: break-word;">
                            <span>@Html.DisplayFor(m => m.LegalEntityName, new { @class = "form-control" })</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">501-C3 Number:</label>
                        <div class="col-sm-8 control-label wrapcontent" style="overflow-wrap: break-word;">
                            <span>@Html.DisplayFor(m => m.Number501_C3, new { @class = "form-control" })</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Charity Name:</label>
                        <div class="col-sm-8 control-label wrapcontent" style="overflow-wrap: break-word;">
                            <span>@Html.DisplayFor(m => m.CharityName, new { @class = "form-control" })</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Charity Logo:</label>
                        <div class="col-sm-8 control-label">
                            <span><img src="@Model.CharityLogoFullPath" id="imgCharityLogo" width="100" height="100" /></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Charity Address:</label>
                        <div class="col-sm-8 control-label wrapcontent" style="overflow-wrap: break-word;">
                            <span>@Html.DisplayFor(m => m.Address), @Html.DisplayFor(m => m.City, new { @class = "form-control" }), @Html.DisplayFor(m => m.State) @Html.DisplayFor(m => m.Zip)</span>
                        </div>

                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Category:</label>
                        <div class="col-sm-8 control-label">
                            <span>@Html.DisplayFor(m => m.CategoryName, new { @class = "form-control" })</span>
                        </div>
                    </div>
                </div>
            </div>
            @*<div class="col-xs-12 padding-zero bank-info">
                <div class="form-group pull-right agree bank">
                    <label class="info">Bank Information</label>
                    @Html.ActionLink("View", "ManageBilling", "Billing", new { token = @Model.CreditCardDetails.Token }, new { @class = "btn btn-default active", @title = "View Bank Information" })
                </div>
            </div>*@
            @*@if (@Model.CreditCardDetails != null && !string.IsNullOrEmpty(Model.CreditCardDetails.Token))
            {

                <div class="col-xs-12 padding-zero bank-info">
                    <div class="form-group pull-right agree bank">
                        <label class="info">Bank Information</label>
                        
                        @Html.ActionLink("Edit", "AddEditCreditCard", "Payment", new { token = @Model.CreditCardDetails.Token }, new { @class = "btn btn-default active", @title = "Edit Bank Information" })
                        &nbsp; <a onclick="javascript: return ConfirmDelete();" href="@Url.RouteUrl("Default", new { controller="Charity/Payment" , action="DeleteCreditCard" , token=@Model.CreditCardDetails.Token, chrityid=@Model.CharityId })" class="btn btn-default btn-lg active prev" title="Delete Bank Information"><i class=" fa fa-trash"></i> Delete</a>
                    </div>
                </div>
                <div class="row">
                    @Html.Partial("~/Areas/Charity/Views/Payment/_CreditCardDetails.cshtml", Model)
                </div>
            }
            else
            {
                <div class="col-xs-12 padding-zero bank-info">
                    <div class="form-group pull-right agree bank">
                        <label class="info">Bank Information</label>
                        @Html.ActionLink("Add", "Step2", "Payment", new { CharityId = @Model.CharityId, fromAccountInfo = true }, new { @class = "btn btn-default active", @title = "Add Bank Information" })
                    </div>
                </div>
            }*@
            @*<button type="submit" class="btn btn-default btn-lg active">View</button>
        <button type="submit" class="btn btn-default btn-lg active prev">Edit</button>*@
        </div>

    </div>
}

<script src="~/Areas/Charity/Scripts/Payment.js"></script>


<script>
    $(document).ready(function () {
        $(".menu-item a").removeClass("active");//this will remove the active class from
        //previously active menu item
        $('#A3').addClass('active');
        
        var height = $('.account-main').height();       
        
        $("#divGeneralInfo").css("cssText", "height: " + height + "px !important;");
        $("#divOtherInfo").css("cssText", "height: " + height + "px !important;");

    });

    

</script>